const songs = [
  "Lady '95",
  "The Best of Times",
  "Lorelei",
  "Too Much Time On My Hands",
  "Babe",
  "Fooling Yourself (The Angry Young Man)",
  "Show Me The Way",
  "Renegade",
  "Come Sail Away",
  "Blue Collar Man (Long Nights)",
  "The Grand Illusion",
  "Crystal Ball",
  "Suite Madame Blue",
  "Miss America",
  "Mr. Roboto",
  "Don't Let It End",
  "Great White Hope",
  "I'm O.K.",
  "Sing for the Day",
  "The Message",
  "Lords of the Ring",
  "Blue Collar Man",
  "Queen of Spades",
  "Renegade",
  "Pieces of Eight",
  "Aku Aku",
  "Movement for the Common Man: Children of the Land / Street ...: Chlidren Of The Land / Fanfare For The Common Man / Street Collage / Mother Nature's Matinee",
  "Right Away",
  "What Has Come Between Us",
  "Best Thing",
  "Quick Is the Beat of My Heart",
  "After You Leave Me",
  "You Need Love",
  "Lady",
  "A Day",
  "You Better Ask",
  "Little Fugue in \"G\"",
  "Father O.S.A.",
  "Earl of Roseland",
  "I'm Gonna Make You Feel It",
  "Unfinished Song",
  "Witch Wolf",
  "The Grove of Eglatine",
  "Young Man",
  "As Bad as This",
  "Winner Takes All",
  "22 Years",
  "Jonas Psalter",
  "The Serpent Is Rising",
  "Krakatoa",
  "Hallelujah Chorus",
  "Rock & Roll Feeling",
  "Havin' a Ball",
  "Golden Lark",
  "A Song for Suzanne",
  "A Man Like Me",
  "Lies",
  "Evil Eyes",
  "Southern Woman",
  "Christopher, Mr. Christopher",
  "Man of Miracles",
  "Light Up",
  "Lorelei",
  "Mother Dear",
  "Lonely Child",
  "Midnight Ride",
  "Born For Adventure",
  "Prelude 12",
  "Suite Madame Blue",
  "The Grand Illusion",
  "Fooling Yourself (The Angry Young Man)",
  "Superstars",
  "Come Sail Away",
  "Miss America",
  "Man in the Wilderness",
  "Castle Walls",
  "The Grand Finale",
  "Lights",
  "Why Me",
  "Babe",
  "Never Say Never",
  "Boat On The River",
  "Borrowed Time",
  "First Time",
  "Eddie",
  "Love In The Midnight",
  "Best Thing",
  "You Need Love",
  "Lady",
  "Winner Take All",
  "Rock & Roll Feeling",
  "Light Up",
  "Lorelei",
  "Prelude 12",
  "Suite Madame Blue",
  "Shooz",
  "Mademoiselle",
  "Crystal Ball",
  "The Grand Illusion",
  "Fooling Yourself (The Angry Young Man)",
  "Come Sail Away",
  "Miss America",
  "Man In The Wilderness",
  "Blue Collar Man (Long Nights)",
  "Sing For The Day",
  "Renegade",
  "Pieces Of Eight",
  "Lights",
  "Babe",
  "Borrowed Time",
  "Boat On The River",
  "A.D. 1928",
  "Rockin' The Paradise",
  "Too Much Time On My Hands",
  "The Best Of Times",
  "Snowblind",
  "Mr. Roboto",
  "Love Is The Ritual",
  "Show Me The Way",
  "Dear John",
  "One With Everything",
  "Put Me On",
  "Mademoiselle",
  "Jennifer",
  "Crystal Ball",
  "Shooz",
  "This Old Man",
  "Clair De Lune / Ballerina",
  "Mr. Roboto",
  "Cold War",
  "Don't Let It End",
  "High Time",
  "Heavy Metal Poisoning",
  "Just Get Through This Night",
  "Double Life",
  "Haven't We Been Here Before",
  "Don't Let It End - (reprise)",
  "A.D. 1928",
  "Rockin' The Paradise",
  "Too Much Time On My Hands",
  "Nothing Ever Goes As Planned",
  "The Best Of Times",
  "Lonely People",
  "She Cares",
  "Snowblind",
  "Half-Penny, Two-Penny",
  "A.D. 1958",
  "State Street Sadie",
  "The Grand Illusion",
  "Fooling Yourself (the Angry Young Man)",
  "Lorelei",
  "Sing For the Day",
  "Crystal Ball",
  "Come Sail Away",
  "Difference In the World",
  "Blue Collar Man (Long Nights)",
  "Miss America",
  "Renegade",
  "Queen of Spades",
  "Boat On the River",
  "Too Much Time On My Hands",
  "Snowblind",
  "Coming of Age",
  "High Enough",
  "The Grand Illusion",
  "Fooling Yourself (The Angry Young Man)",
  "Superstars",
  "Come Sail Away",
  "Miss America",
  "Man In The Wilderness",
  "Castle Walls",
  "The Grand Finale",
  "Great White Hope",
  "I'm Okay",
  "Sing For The Day",
  "The Message",
  "Lords Of The Ring",
  "Blue Collar Man (Long Nights)",
  "Queen Of Spades",
  "Renegade",
  "Pieces Of Eight",
  "Aku-Aku",
  "Overture",
  "Gone Gone Gone",
  "Hundred Million Miles From Home",
  "Trouble at the Big Show",
  "Locomotive",
  "Radio Silence",
  "The Greater Good",
  "Time May Bend",
  "Ten Thousand Ways",
  "Red Storm",
  "All Systems Stable",
  "Khedive",
  "The Outpost",
  "Mission to Mars",
  "Blue Collar Man (Long Nights)",
  "Come Sail Away",
  "Babe",
  "Mr. Roboto",
  "Fooling Yourself (The Angry Young Man)",
  "Lorelei",
  "Renegade",
  "Too Much Time On My Hands",
  "Mademoiselle",
  "Snowblind",
  "Lady",
  "Show Me The Way",
  "Oh Pretty Woman",
  "Young Girl",
  "Mr. Tambourine Man",
  "You've Made Me So Very Happy",
  "Kind Of A Drag",
  "San Francisco",
  "Little Green Apples",
  "Flowers On The Wall",
  "A Boy Named Sue",
  "Blue Velvet",
  "It's Your Thing",
  "Red Rubber Ball",
  "Hey Little Cobra",
  "Kicks",
  "Greenfields",
  "Can't Get Used To Losing You",
  "Don't Worry",
  "Sink The Bismarck",
  "Big Bad John",
  "Theme From \"A Summer Place\"",
  "Hold Your Head Up",
  "More Than A Feeling",
  "Black Magic Woman",
  "Rock & Roll Hoochie Koo",
  "Love Train",
  "Play That Funky Music",
  "I Go Crazy",
  "Brandy (You're A Fine Girl)",
  "Best Of My Love",
  "Long Cool Woman (In A Black Dress)",
  "Wildfire",
  "Me And Mrs. Jones",
  "(Don't Fear) The Reaper",
  "Lowdown",
  "Got To Be Real",
  "Longer",
  "Shining Star",
  "Hold The Line",
  "Lean On Me",
  "Baby Hold On To Me",
  "Takin' Care Of Business",
  "Free Bird",
  "Renegade",
  "Baby I Love Your Way",
  "Jackie Blue",
  "Love Will Find A Way",
  "Easy",
  "Never Can Say Goodbye",
  "I've Got The Music In Me",
  "Jungle Boogie",
  "Fire",
  "Wasted Days And Wasted Nights",
  "Black And White",
  "Outa-Space",
  "Boogie Down",
  "Fairytale",
  "The Way That I Want To Touch You",
  "Go Away Little Girl",
  "I'll Be Good To You",
  "We're All Alone",
  "Too Much Time On My Hands",
  "Come Sail Away",
  "Blue Collar Man (Long Nights)",
  "Lorelei",
  "Fooling Yourself (The Angry Young Man)",
  "Mr. Roboto",
  "Boat On The River",
  "The Best of Times",
  "Mademoiselle",
  "Babe",
  "Show Me The Way",
  "Intro / 1978",
  "The Grand Illusion",
  "Fooling Yourself (the Angry Young Man)",
  "Superstars",
  "Come Sail Away",
  "Miss America",
  "Man In the Wilderness",
  "Castle Walls",
  "The Grand Finale",
  "Great White Hope",
  "I'm Okay",
  "Sing For the Day",
  "The Message",
  "Lords of the Ring",
  "Blue Collar Man (Long Nights)",
  "Queen of Spades",
  "Renegade",
  "Pieces of Eight",
  "Aku - Aku",
  "Putting On the Show",
  "More Than A Feeling",
  "Evil Woman",
  "Come Sail Away",
  "Taking Care Of Business",
  "American Woman",
  "I Just Want To Celebrate",
  "Black Magic Woman",
  "Never Been To Spain",
  "Green Eyed Lady",
  "We're An American Band",
  "Sweet Home Alabama",
  "So Into You",
  "Help Is On Its Way",
  "Dust In The Wind",
  "Owner Of A Lonely Heart",
  "Mr. Roboto",
  "Everybody Wants To Rule The World",
  "Call Me",
  "Addicted To Love",
  "Sweet Dreams (Are Made Of This)",
  "You Keep Runnin' Away",
  "Something About You",
  "Gemini Dream",
  "In A Big Country",
  "New Sensation",
  "Don't Go",
  "The Grand Illusion",
  "Fooling Yourself (The Angry Young Man)",
  "Superstars",
  "Come Sail Away",
  "Miss America",
  "Man in the Wilderness",
  "Castle Walls",
  "The Grand Finale",
  "Renegade",
  "Come Sail Away",
  "Mr. Roboto",
  "Babe",
  "Fooling Yourself (The Angry Young Man)",
  "Lorelei",
  "Blue Collar Man (Long Nights)",
  "Too Much Time on My Hands",
  "Lady",
  "Snowblind",
  "Mademoiselle",
  "Show Me the Way",
  "Light Up",
  "Crystal Ball",
  "Miss America",
  "Boat on the River",
  "Borrowed Time",
  "Suite Madame Blue",
  "The Grand Illusion",
  "Love Is the Ritual",
  "The Best of Times",
  "Man In the Wilderness",
  "Shooz",
  "Lights",
  "Light Up",
  "Lorelei",
  "Mother Dear",
  "Lonely Child",
  "Midnight Ride",
  "Born for Adventure",
  "Prelude",
  "Suite Madame Blue",
  "Put Me On",
  "Mademoiselle",
  "Jennifer",
  "Crystal Ball",
  "Shooz",
  "This Old Man",
  "Clair de Lune / Ballerina",
  "Kilroy Was Here [Short Film][Multimedia Track]",
  "Mr. Roboto [DVD]",
  "Rockin' the Paradise [DVD]",
  "Blue Collar Man (Long Nights) [DVD]",
  "Snowblind [DVD]",
  "Too Much Time on My Hands [DVD]",
  "Don't Let It End [DVD]",
  "Heavy Metal Poisoning [DVD]",
  "Cold War [DVD]",
  "The Best of Times [DVD]",
  "Come Sail Away [DVD]",
  "Renegade [DVD]",
  "Haven't We Been Here Before? [DVD]",
  "Don't Let It End (Reprise) [DVD]",
  "Come Sail Away [Promo Video]",
  "Borrowed Time [Promo Video]",
  "Babe [Promo Video]",
  "Boat on the River [Promo Video]",
  "A. D. 1928 / Rockin' the Paradise [Music Video]",
  "The Best of Times [Music Video]",
  "Too Much Time on My Hands [Music Video]",
  "Mr. Roboto [Music Video]",
  "Don't Let It End [Music Video]",
  "Heavy Metal Poisoning [Music Video]",
  "Haven't We Been Here Before? [Music Video]",
  "Music Time [Music Video]",
  "Great White Hope",
  "I'm Ok",
  "Sing for the Day",
  "The Message",
  "Lords of the Ring",
  "Blue Collar Man (Long Nights)",
  "Queen of Spades",
  "Renegade",
  "Pieces of Eight",
  "Aku-Aku",
  "Mr. Roboto",
  "Cold War",
  "Don't Let It End",
  "High Time",
  "Heavy Metal Poisoning",
  "Just Get Through This Night",
  "Double Life",
  "Haven't We Been Here Before?",
  "Don't Let It End (Reprise)",
  "Two Tickets To Paradise",
  "Uncle Tom's Cabin",
  "In My Dreams",
  "Babe",
  "32 Pennies",
  "1000 Points Of Light",
  "Just Got Lucky",
  "Too Much Time On My Hands",
  "Baby Hold On",
  "Roundabout",
  "The Grand Illusion",
  "Fooling Yourself (The Angry Young Man)",
  "Superstars",
  "Come Sail Away",
  "Miss America",
  "Man In The Wilderness",
  "Castle Walls",
  "The Grand Finale",
  "Great White Hope",
  "I'm O.K.",
  "Sing For The Day",
  "The Message",
  "Lords Of The Ring",
  "Blue Collar Man (Long Nights)",
  "Queen Of Spades",
  "Renegade",
  "Pieces Of Eight",
  "Aku-Aku",
  "A.D. 1928",
  "Rockin' The Paradise",
  "Too Much Time On My Hands",
  "Nothing Ever Goes As Planned",
  "The Best Of Times",
  "Lonely People",
  "She Cares",
  "Snowblind",
  "Half Penny Two Penny",
  "A.D. 1958",
  "State Street Sadie",
  "Mr. Roboto",
  "Cold War",
  "Don't Let It End",
  "High Time",
  "Heavy Metal Poisoning",
  "Just Get Through This Night",
  "Double Life",
  "Haven't We Been Here Before?",
  "Don't Let It End",
  "Lights",
  "Why Me",
  "Babe",
  "Never Say Never",
  "Boat On The River",
  "Borrowed Time",
  "First Time",
  "Eddie",
  "Love In The Midnight",
  "Lights",
  "Why Me",
  "Babe",
  "Never Say Never",
  "Boat On the River",
  "Borrowed Time",
  "First Time",
  "Eddie",
  "Love In the Midnight",
  "Magic Man",
  "Hello It's Me",
  "Everything You've Done Wrong",
  "Ce Matin La",
  "The Air That I Breathe",
  "How Can You Mend a Broken Heart?",
  "Alone Again (Naturally)",
  "I'm Not in Love",
  "A Dream Goes on Forever",
  "Crazy On You",
  "Playground Love (Main Theme)",
  "Come Sail Away",
  "Light Up",
  "Lorelei",
  "Mother Dear",
  "Lonely Child",
  "Midnight Ride",
  "Born For Adventure",
  "Prelude 12",
  "Suite Madame Blue",
  "The Grand Illusion",
  "Too Much Time On My Hands",
  "Fooling Yourself (The Angry Young Man)",
  "Lady",
  "Suite Madame Blue",
  "Light Up",
  "Crystal Ball",
  "Superstars",
  "Blue Collar Man (Long Nights)",
  "Come Sail Away",
  "Rockin' the Paradise",
  "Renegade",
  "Lights",
  "Why Me",
  "Babe",
  "Never Say Never",
  "Boat on the River",
  "Borrowed Time",
  "First Time",
  "Eddie",
  "Love in the Midnight",
  "Lights 04:38",
  "Why Me 03:53",
  "Babe 04:25",
  "Never Say Never 03:07",
  "Boat On A River 03:10",
  "Borrowed Time 04:58",
  "First Time 04:23",
  "Eddie 04:15",
  "Love In The Midnight 05:22",
  "Blue Suede Shoes",
  "Just Walking In The Rain",
  "Sixteen Tons",
  "Rock And Roll Waltz",
  "Standing On The Corner",
  "The Great Pretender",
  "Hot Diggity",
  "Singing The Blues",
  "Allegheny Moon",
  "The Poor People Of Paris",
  "The Wayward Wind",
  "I Almost Lost My Mind",
  "Born To Be With You",
  "Canadian Sunset",
  "Dungaree Doll",
  "The Green Door",
  "Ivory Tower",
  "Band Of Gold",
  "Lisbon Antigua",
  "Whatever Will Be, Will Be (Que Sera, Sera)",
  "Takin' Care Of Business",
  "Free Bird",
  "Renegade",
  "Baby I Love Your Way",
  "Jackie Blue",
  "Love Will Find A Way",
  "Easy",
  "Never Can Say Goodbye",
  "I've Got The Music In Me",
  "Jungle Boogie",
  "Fire",
  "Wasted Days And Wasted Nights",
  "Black And White",
  "Outa-Space",
  "Boogie Down",
  "Fairytale",
  "The Way That I Want To Touch You",
  "Go Away Little Girl",
  "I'll Be Good To You",
  "We're All Alone",
  "One Step Beyond",
  "New Sensation",
  "She Drives Me Crazy",
  "Venus",
  "Major Tom (Coming Home)",
  "Chains Of Love",
  "New Song",
  "Two Hearts",
  "Shake Your Love",
  "Fascinated"
  ];

  export default songs;

